#!/bin/bash

# Prior to running this, the user has jsut seen:
# "   Copying source image:  OK"
# So make sure you indent any output with three spaces to make
# it line up.
#echo "   Display some output here about stuff"
