# Default theme makefile. Mostly for testing.
FORCEDERROR=
ifdef FORCEDERROR
$(error Error forced by setting FORCEDERROR to $(FORCEDERROR) in $(lastword $(MAKEFILE_LIST)))
endif

# Add a file that needs to be generated
#THEMEFILES += herp/the/derp

$(THEMEDESTDIR)/herp/the/derp:
	@echo I am doing nothing
