#!/bin/sh
PREREQ=""
prereqs() {
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac
. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

# Add r8152 and i2c-dev to the initramfs. We don't force load r8152,
# as that will get loaded on demand, but i2c-dev DOES need to be
# force loaded, as it can't be auto-probed
manual_add_modules r8152
force_load i2c-dev

# executable to copy to initramfs, with library dependencies
copy_exec /usr/lib/x86_64-linux-gnu/libnss_dns.so.2

# missing fscks in initramfs
copy_exec /usr/sbin/fsck
copy_exec /usr/sbin/fsck.ext2
copy_exec /usr/sbin/fsck.ext3
copy_exec /usr/sbin/fsck.ext4
copy_exec /usr/sbin/fsck.msdos

# This is used to do very early repairs to the OS. It ended up just being easier
# to add it here than rewrite everything.
copy_exec /usr/bin/bash

# copy other files ("other" here is a file type, so do not delete this keyword)
copy_file other /etc/ssl/certs/ca-certificates.crt
