
src/%/.git:
	if [ ! -d $(@D) ]; then mkdir -p src; git clone $(GITSRC_$*) $(@D); fi
	cd $(@D) && git pull

$(SRCDIR)/% src/%:
	wget $(WGETURL_$*) -O $@; if [ ! -s $@ ]; then echo 'Could not download $@, deleting'; rm -f $@; exit 1; fi

