# Build the asterisk debs
ASTROOT=$(BUILDROOT)/asteriskbuild
ASTMAKEFILE=$(ASTROOT)/Makefile

include asteriskbuild/Makefile

PREREQS += $(ALLASTDEBS)

$(ASTMAKEFILE): | /usr/bin/docker
	@echo '$(ASTROOT) does not exist, this is a submodule. Fix'.
	@exit 99

/usr/bin/docker:
	@echo Docker is not installed. Install docker.
	@exit 99

